# Generated by Django 4.1 on 2022-11-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
